### ISSUE TITLE
Firefox / Safari / iOS Safari Browser Support

### ISSUE THREAD

**Issue by paulreimer** [MakerLabsVan/makerlabs-acm#4]
Currently only Google Chrome browsers are officially supported. Things like searching for users does not work in Safari, and uploaded photos are not visible in Firefox.

All critical features that work in Chrome, should also work in other browsers that are used by CMs / MakerLabs admins.

**Comment by paulreimer** [comment]
Updated this issue based on #7 which appears to be an iOS Safari-specific issue.

**Comment by digitalpixie** [comment]
Low priority, Natalie informed all CMs by email to use Chrome (sept 22)
