### ISSUE TITLE
Recently Created Maker Profiles Not Immediately Available For Search

### ISSUE THREAD

**Issue by paulreimer** [MakerLabsVan/makerlabs-acm#5]
After adding a new maker profile, the new maker does not get added to the search bar. As a workaround, a page refresh is required to get the latest full list of makers.

One possible fix, could address the issue so a single user can see the maker profile they just added.

Another, more involved fix level, could resolve the issue more completely and update the search box for all users (even different users with different browser windows open).

**Comment by digitalpixie** [comment]
CMs please refresh the page before searching 
Communicated by Natalie Sept 22 via email 
Closing the ticket
