### ISSUE TITLE
Activity not consistently logged when fob is tapped 

### ISSUE THREAD

**Issue by digitalpixie** [MakerLabsVan/makerlabs-acm#8]
Member taps fob at front desk and it registers on the ACM interface web page but not recorded in the activity tab of the spreadsheet. Happens some times not all the time. Contact Alyssa for more details.

**Comment by paulreimer** [comment]
Resolved via the changes to spreadsheet query (matching User to Tag ID) by using a fresh connection for each request and not re-using connections. "Socket hang up" error no longer occurs.
