### ISSUE TITLE
Laser Cutters Machine ID 

### ISSUE THREAD

**Issue by digitalpixie** [MakerLabsVan/makerlabs-acm#9]
Please add machine IDs for CASE and TARS laser cutters. The Laser Lab 101 course checkbox should no longer be connected to the activity of a laser cutter. 

CMs must check Laserlab 101 if member completes the course AND check the specific machine that a member has access to.

Please email hello@makerlabs with estimate for this work before completing.

Thank you! 

Nat

**Comment by paulreimer** [comment]
This was done during setup of TARS and CASE, no future work required.
